### ISSUE TITLE
Finish icons

### ISSUE THREAD

**Issue by zapSNH** [zapSNH/ZTheme#1]
## Problem
A ton of textures don't have icons at all since I'm pretty bad at making them.
If you can make any icons then please put them in this issue or open a PR.
Icons should be monochrome and should preferably (loosely) follow a modern-ish design system (like Firefox Photon or Google Material Design)

Here's a list of textures that need icons:

##
Save icons
- [x] The career, (#3)
- [x] science, and (#3)
- [x] sandbox mode icons (#3)
##
- [x] The PAW pin icon
##
R&D icons
- [x] ~The research tech icon~
- [x] The research tab icon
- [x] The archive tab icon
##
The science dialog icons:
- [x] Keep data
- [x] Research lab
- [x] Reset data
- [x] Transmit data
##
VAB icons
- [x] Load ship (#3)
- [x] Save ship (#3)
- [x] Action Groups (#3)
- [x] Construction Mode (#3)
- [x] Cargo Mode (#3)
- [x] Switch Editors (#3)
- [x] Steam icon
##
- [x] KAL icons
    There's a lot of these icons.
## Low Priority
- [ ] -Mission Builder icons- Impossible/Very hard as of now

##

Most of these already have backgrounds so you/I only need to make the icons.

**Comment by OnlyLightMatters** [comment]
Hi all.
I'm taking the VAB Icons. Will make a pull request by tomorrow evening.

**Comment by OnlyLightMatters** [comment]
![SampleIconsKSPVAB](https://github.com/zapSNH/ZTheme/assets/48958923/4b44c091-76fc-4952-9b5e-6f81a11ceb1b)
The Exit Red Icon would have to be normalized regarding a very simple flat design I propose with the minimum colors possible.
Feel free to reject this proposal, deisgn is a matter of taste and everyone has different ones.

**Comment by zapSNH** [comment]
> ![SampleIconsKSPVAB](https://user-images.githubusercontent.com/48958923/241800259-4b44c091-76fc-4952-9b5e-6f81a11ceb1b.png) The Exit Red Icon would have to be normalized regarding a very minimalistic flat design I propose with the minimum colors possible. Feel free to reject this proposal, design is a matter of taste and everyone has different ones.

That looks awesome! I'll have to add this later since I have stuff to do.

**Comment by OnlyLightMatters** [comment]
Okay thanks for your feedback.
I still have AG / Switch hangar / build icons to be done.
I will probably shorten the lenth of the arrows for the save and load icons.
