### ISSUE TITLE
CKAN Missing Dependency

### ISSUE THREAD

**Issue by afyber** [zapSNH/ZTheme#11]
With 1.3.1.1 CKAN seems to be missing the HUD Replacer dependency.

**Comment by zapSNH** [comment]
CKAN isn't supposed to have a 1.3.1.1 release for ZTheme...

**Comment by zapSNH** [comment]
It seems that this [NetKAN commit](https://github.com/KSP-CKAN/NetKAN/commit/f273da29e2ba472c529dae6c777a7c57b67db651) added GitHub release links to spacedock mods which somehow broke the dependency installation.

**Comment by zapSNH** [comment]
Should be fixed now.
