### ISSUE TITLE
Adding to CKAN

### ISSUE THREAD

**Issue by minihic** [zapSNH/ZTheme#5]
Hey, I really love this mod, breaths so much new life into the decade old KSP interface. How feasible would it be to add this mod to CKAN? You're updating it often and it would be more streamlined to have it in CKAN. Thanks for considering!

**Comment by zapSNH** [comment]
There's already a PR on the netkan repo about this! I'm just waiting for them to review it.
https://github.com/KSP-CKAN/NetKAN/pull/9694

**Comment by HebaruSan** [comment]
Sorry for the delay, it should be in CKAN within the next 35 minutes.
