### ISSUE TITLE
Purchase bouton - editor - career mode

### ISSUE THREAD

**Issue by s4bm** [zapSNH/ZTheme#9]
<img width="1470" alt="career mode" src="https://github.com/zapSNH/ZTheme/assets/161365108/5beab9ec-1963-442e-9b5c-6d94de5fe01f">

Hello zapSNH, I really love your mode !

I've just seen on a career mode, one button is still on the stock version. It is the "Purchase" button of a part on the VAB/SPH, it is displayed like the capture only when a part is too expensive.

I didn't try in the tech tree in the R&D but the issue could be also here.

**Comment by zapSNH** [comment]
I've released v1.1.3 which should fix this. Unfortunately, https://spacedock.info is down so yo won't get so see the release on CKAN right away.
